### ISSUE TITLE
Lack of explanation

### ISSUE THREAD

**Issue by Zwergomaniac** [Markcanfly/shifts#1]
I think this project needs a little explanation on how to use the program....
How do i input my Shifts and employees?

**Comment by markvincevarga** [comment]
Execute the main.py script with the data file specified as a command line parameter.

`python main.py data.json`

You can find an example of the data format in https://github.com/Markcanfly/shifts/blob/c1f92c3374639e68b16c37b09438d038338c1f6c/data.py#L92

Currently this is a specific solution to certain problem, and right now I unfortunately have no time to make it generally useful. Thanks for the reminder though! I have added the MIT license, and will archive the repository.
